apiVersion: v1
kind: Service
metadata:
  name: vivaad-service
  namespace: vivaad
  labels:
    run: nginx
spec:
  type: NodePort
  ports:
  - port: 80          # Port exposed within the cluster
    targetPort: 80  # Port on the pods
    nodePort: 30090  # Port accessible externally on each node
  selector:
    run: nginx
